### ISSUE TITLE
Рассмотрения тесты 

### ISSUE THREAD

**Issue by akram8008** [AlisherFozilov/priority-queue#1]
Привет, я изучал твой код.И я думаю что у тебя две часть кода работают неправильно. Первая это сортировка и второй это индексация. 
       -В Сортировке у тебя сортируют по приоритету но не рассматривает ситуации когда приоритеты равны (в этом ситуации  надо проверить  их по  время прибытия в очередь )
       - Во втором рассмотрим такую ситуацию когда в очередь есть 6 человек в виде:
                    - value:"Karim1" index=1, priority = 200
                    - value:"Karim2" index=2, priority = 180
                    - value:"Karim3" index=3, priority = 160
                    - value:"Karim4" index=4, priority = 150
                    - value:"Karim5" index=5, priority = 140
                    - value:"Karim6" index=6, priority = 120
Когда вызывается метод Dequeue() два раза то иза очереди удаляется первый и второй, и после этого добавляется еще  один _(Enqueue("Karim7"),100)_ в очередь то у него index будут вставляться  из lst.length(). То есть 4. А в очереди есть уже элемент с такими индексами. Неправильно будет когда у тебя в очереде две элементы который имеют одинаковый индекса.  В "поиске элемента" неправильно  будет находить  элементы, так как ты ищешь по индексу.  

Поправь если я где то ошибаюсь.....

**Comment by AlisherFozilov** [comment]
Да, действительно, второе замечание верно. Индексы расставлялись неверно. Исправил и добавил дополнительный тест для проверки корректности индексов.
Насчёт первого замечания касательно случая с элементами с одинаковым приоритетом могу сказать, что программа работает верно. Как минимум из-за использования sort.Stable, а не sort.Sort. Для того, чтобы показать правильную работоспособность программы был добавлен дополнительный тест для проверки этого случая.

Большое спасибо за проверку кода. Весьма благодарен Вам!
Если есть дополнительные замечания, с радостью приму:)
