### ISSUE TITLE
При удалении возвращайте удалённый

### ISSUE THREAD

**Issue by coursar** [AlisherFozilov/priority-queue#3]
https://github.com/AlisherFozilov/priority-queue/blob/3ef6965de8cce3364c57d5099a41be5f3aed393f/priority-queue.go#L87

**Comment by AlisherFozilov** [comment]
В чем заключается недостаток разделения метода возвращения очередного элемента от метода удаления этого элемента? Это по причине того, что всегда после получения нужного элемента мы все равно его должны удалить?

https://github.com/AlisherFozilov/priority-queue/blob/872747a3705fa2f7693c108a4586b97f24193d9f/priority-queue.go#L80

**Comment by coursar** [comment]
Нет, тут скорее логическая история - вы хотите "забрать" элемент из очереди. Т.е. вы его "удаляете" из очереди и возвращаете вызывающему коду.

Единственное, почему last-то? Разве в очереди не first-должен быть?

**Comment by AlisherFozilov** [comment]
Метод dequeue() очереди возвращает и удаляет элемент.
https://github.com/AlisherFozilov/priority-queue/blob/dd7d6475d49ee3a6546b2a42fb505d4cc67d8768/priority-queue.go#L21-L29

С именами first и last накосячил. Пускай будут "первый и второй с конца" соответственно :)
